const $=s=>document.querySelector(s);
let colors=[], current="#7C5CFC", hue=260, sat=.5, val=.99;

const cssNames={AliceBlue:"#F0F8FF",AntiqueWhite:"#FAEBD7",Aqua:"#00FFFF",Aquamarine:"#7FFFD4",Azure:"#F0FFFF",Beige:"#F5F5DC",Bisque:"#FFE4C4",Black:"#000000",BlanchedAlmond:"#FFEBCD",Blue:"#0000FF",BlueViolet:"#8A2BE2",Brown:"#A52A2A",BurlyWood:"#DEB887",CadetBlue:"#5F9EA0",Chartreuse:"#7FFF00",Chocolate:"#D2691E",Coral:"#FF7F50",CornflowerBlue:"#6495ED",Crimson:"#DC143C",Cyan:"#00FFFF",DarkBlue:"#00008B",DarkCyan:"#008B8B",DarkGoldenRod:"#B8860B",DarkGray:"#A9A9A9",DarkGreen:"#006400",DarkGrey:"#A9A9A9",DarkKhaki:"#BDB76B",DarkMagenta:"#8B008B",DarkOliveGreen:"#556B2F",DarkOrange:"#FF8C00",DarkOrchid:"#9932CC",DarkRed:"#8B0000",DarkSalmon:"#E9967A",DarkSeaGreen:"#8FBC8F",DarkSlateBlue:"#483D8B",DarkSlateGray:"#2F4F4F",DarkSlateGrey:"#2F4F4F",DarkTurquoise:"#00CED1",DarkViolet:"#9400D3",DeepPink:"#FF1493",DeepSkyBlue:"#00BFFF",DimGray:"#696969",DodgerBlue:"#1E90FF",FireBrick:"#B22222",FloralWhite:"#FFFAF0",ForestGreen:"#228B22",Fuchsia:"#FF00FF",Gainsboro:"#DCDCDC",GhostWhite:"#F8F8FF",Gold:"#FFD700",GoldenRod:"#DAA520",Gray:"#808080",Green:"#008000",GreenYellow:"#ADFF2F",Grey:"#808080",HoneyDew:"#F0FFF0",HotPink:"#FF69B4",IndianRed:"#CD5C5C",Indigo:"#4B0082",Ivory:"#FFFFF0",Khaki:"#F0E68C",Lavender:"#E6E6FA",LavenderBlush:"#FFF0F5",LawnGreen:"#7CFC00",LemonChiffon:"#FFFACD",LightBlue:"#ADD8E6",LightCoral:"#F08080",LightCyan:"#E0FFFF",LightGoldenRodYellow:"#FAFAD2",LightGray:"#D3D3D3",LightGreen:"#90EE90",LightGrey:"#D3D3D3",LightPink:"#FFB6C1",LightSalmon:"#FFA07A",LightSeaGreen:"#20B2AA",LightSkyBlue:"#87CEFA",LightSlateGray:"#778899",LightSlateGrey:"#778899",LightSteelBlue:"#B0C4DE",LightYellow:"#FFFFE0",Lime:"#00FF00",LimeGreen:"#32CD32",Linen:"#FAF0E6",Magenta:"#FF00FF",Maroon:"#800000",MediumAquamarine:"#66CDAA",MediumBlue:"#0000CD",MediumOrchid:"#BA55D3",MediumPurple:"#9370DB",MediumSeaGreen:"#3CB371",MediumSlateBlue:"#7B68EE",MediumSpringGreen:"#00FA9A",MediumTurquoise:"#48D1CC",MediumVioletRed:"#C71585",MidnightBlue:"#191970",MintCream:"#F5FFFA",MistyRose:"#FFE4E1",Moccasin:"#FFE4B5",NavajoWhite:"#FFDEAD",Navy:"#000080",OldLace:"#FDF5E6",Olive:"#808000",OliveDrab:"#6B8E23",Orange:"#FFA500",OrangeRed:"#FF4500",Orchid:"#DA70D6",PaleGoldenRod:"#EEE8AA",PaleGreen:"#98FB98",PaleTurquoise:"#AFEEEE",PaleVioletRed:"#DB7093",PapayaWhip:"#FFEFD5",PeachPuff:"#FFDAB9",Peru:"#CD853F",Pink:"#FFC0CB",Plum:"#DDA0DD",PowderBlue:"#B0E0E6",Purple:"#800080",RebeccaPurple:"#663399",Red:"#FF0000",RosyBrown:"#BC8F8F",RoyalBlue:"#4169E1",SaddleBrown:"#8B4513",Salmon:"#FA8072",SandyBrown:"#F4A460",SeaGreen:"#2E8B57",SeaShell:"#FFF5EE",Sienna:"#A0522D",Silver:"#C0C0C0",SkyBlue:"#87CEEB",SlateBlue:"#6A5ACD",SlateGray:"#708090",SlateGrey:"#708090",Snow:"#FFFAFA",SpringGreen:"#00FF7F",SteelBlue:"#4682B4",Tan:"#D2B48C",Teal:"#008080",Thistle:"#D8BFD8",Tomato:"#FF6347",Turquoise:"#40E0D0",Violet:"#EE82EE",Wheat:"#F5DEB3",White:"#FFFFFF",WhiteSmoke:"#F5F5F5",Yellow:"#FFFF00",YellowGreen:"#9ACD32"};
for(const [name,hex] of Object.entries(cssNames)) colors.push({name,hex});

function hexRgb(hex){hex=hex.replace("#","");if(hex.length===3)hex=hex.split("").map(x=>x+x).join("");if(!/^[0-9a-f]{6}$/i.test(hex))return null;return [parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4),16)]}
function rgbHex(r,g,b){return "#"+[r,g,b].map(x=>Math.round(x).toString(16).padStart(2,"0")).join("").toUpperCase()}
function rgbHsv(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,h=0,s=max?d/max:0,v=max;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,s*100,v*100]}
function hsvRgb(h,s,v){s/=100;v/=100;let c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c,r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return[(r+m)*255,(g+m)*255,(b+m)*255]}
function rgbHsl(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2,d=max-min,h=0,s=0;if(d){s=d/(1-Math.abs(2*l-1));if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,s*100,l*100]}
function rgbCmyk(r,g,b){r/=255;g/=255;b/=255;let k=1-Math.max(r,g,b);if(k>=.999)return[0,0,0,100];return[(1-r-k)/(1-k)*100,(1-g-k)/(1-k)*100,(1-b-k)/(1-k)*100,k*100]}
function srgbLinear(x){x/=255;return x<=.04045?x/12.92:Math.pow((x+.055)/1.055,2.4)}
function rgbOklab(rgb){let [r,g,b]=rgb.map(srgbLinear);let l=.4122214708*r+.5363325363*g+.0514459929*b,m=.2119034982*r+.6806995451*g+.1073969566*b,s=.0883024619*r+.2817188376*g+.6299787005*b;l=Math.cbrt(l);m=Math.cbrt(m);s=Math.cbrt(s);return[.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s]}
function oklch(rgb){let [L,a,b]=rgbOklab(rgb),C=Math.hypot(a,b),H=(Math.atan2(b,a)*180/Math.PI+360)%360;return[L*100,C,H]}
function colorDistance(a,b){let A=rgbOklab(hexRgb(a.hex)||[0,0,0]),B=rgbOklab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function nearestName(hex){let rgb=hexRgb(hex);if(!rgb)return null;let best=null,d=Infinity;for(const c of colors){let dd=colorDistance(c,rgb);if(dd<d){d=dd;best=c}}return{...best,distance:d}}
function setColor(hex){let rgb=hexRgb(hex);if(!rgb)return;current=rgbHex(...rgb);let [h,s,v]=rgbHsv(...rgb);hue=h;sat=s/100;val=v/100;render()}
function render(){let rgb=hexRgb(current),[r,g,b]=rgb,[h,s,v]=rgbHsv(r,g,b),[hh,ss,ll]=rgbHsl(r,g,b),[c,m,y,k]=rgbCmyk(r,g,b),[L,C,H]=oklch(rgb),named=nearestName(current);$("#nativeColor").value=current;$("#hexInput").value=current;$("#swatch").style.background=current;$("#svPicker").style.background=`linear-gradient(to bottom,#0000,#000),linear-gradient(to right,#fff,hsl(${h} 100% 50%))`;$("#pickerCursor").style.left=(s)+"%";$("#pickerCursor").style.top=(100-v)+"%";$("#huePicker").style.setProperty("--hue",h);$("#huePicker").style.setProperty("background",`linear-gradient(to right,red,#ff0,#0f0,#0ff,#00f,#f0f,red)`);$("#colorName").textContent=named?.name||"Unknown";$("#distance").textContent=named?`Nearest match · ${(named.distance*100).toFixed(2)}% distance`:"";const vals=[["HEX",current],["RGB",`${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}`],["HSV",`${h.toFixed(1)}°, ${s.toFixed(1)}%, ${v.toFixed(1)}%`],["HSL",`${hh.toFixed(1)}°, ${ss.toFixed(1)}%, ${ll.toFixed(1)}%`],["HSB",`${h.toFixed(1)}°, ${s.toFixed(1)}%, ${v.toFixed(1)}%`],["CMYK",`${c.toFixed(1)}%, ${m.toFixed(1)}%, ${y.toFixed(1)}%, ${k.toFixed(1)}%`],["OKLCH",`${L.toFixed(4)} ${C.toFixed(4)} ${H.toFixed(1)}°`],["CSS",`rgb(${Math.round(r)} ${Math.round(g)} ${Math.round(b)})`]];$("#values").innerHTML=vals.map(([a,b])=>`<div class="value"><label>${a}</label><code>${b}</code></div>`).join("");$("#formatGrid").innerHTML=vals.map(([a,b])=>`<button class="value" data-copy="${b}"><label>${a}</label><code>${b}</code></button>`).join("");document.querySelectorAll("#formatGrid [data-copy]").forEach(x=>x.onclick=()=>copy(x.dataset.copy));}
function copy(s){navigator.clipboard?.writeText(s);const old=document.activeElement?.innerText;if(old){document.activeElement.innerText="Copied";setTimeout(()=>{try{document.activeElement.innerText=old}catch{}} ,700)}}
function parseCSV(t){return t.split(/\r?\n/).slice(1).map(line=>{let i=line.lastIndexOf(",");let left=line.slice(0,i);let j=left.lastIndexOf(",");let name=left.slice(0,j),hex=left.slice(j+1);return{name,hex}}).filter(x=>x.name&&hexRgb(x.hex))}
function drawPicker(e){let r=$("#svPicker").getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),y=Math.max(0,Math.min(r.height,e.clientY-r.top));setColor(rgbHex(...hsvRgb(hue,x/r.width*100,100-y/r.height*100)))}
$("#svPicker").addEventListener("pointerdown",e=>{e.currentTarget.setPointerCapture(e.pointerId);drawPicker(e)});$("#svPicker").addEventListener("pointermove",e=>{if(e.buttons)drawPicker(e)});
$("#huePicker").addEventListener("pointerdown",e=>{let r=e.currentTarget.getBoundingClientRect();hue=Math.max(0,Math.min(360,(e.clientX-r.left)/r.width*360));setColor(rgbHex(...hsvRgb(hue,sat*100,val*100)))});
$("#nativeColor").oninput=e=>setColor(e.target.value);$("#hexInput").onchange=e=>{let v=e.target.value.trim();if(!v.startsWith("#"))v="#"+v;if(hexRgb(v))setColor(v);else e.target.value=current};
$("#copyHex").onclick=()=>copy(current);$("#copyAll").onclick=()=>copy($("#values").innerText);
$("#randomBtn").onclick=()=>setColor(rgbHex(Math.random()*256,Math.random()*256,Math.random()*256));
$("#clearSearch").onclick=()=>{$("#search").value="";$("#searchResults").hidden=true;$("#clearSearch").hidden=true};
$("#search").addEventListener("input",e=>{let q=e.target.value.trim().toLowerCase();$("#clearSearch").hidden=!q;if(hexRgb(q)){$("#searchResults").hidden=true;setColor(q);return}if(!q){$("#searchResults").hidden=true;return}let hits=colors.filter(c=>c.name.toLowerCase().includes(q)).slice(0,12);$("#searchResults").innerHTML=hits.length?hits.map(c=>`<div class="search-item" data-hex="${c.hex}"><i class="mini-swatch" style="background:${c.hex}"></i><strong>${c.name}</strong><span>${c.hex}</span></div>`).join(""):`<div class="search-item"><span>No matching color names.</span></div>`;$("#searchResults").hidden=false;document.querySelectorAll(".search-item[data-hex]").forEach(x=>x.onclick=()=>{setColor(x.dataset.hex);$("#search").value=x.querySelector("strong").textContent;$("#searchResults").hidden=true})});
function renderGrid(){let shown=colors.slice(0,120);$("#count").textContent=`${colors.length.toLocaleString()} names`;$("#colorGrid").innerHTML=shown.map(c=>`<button class="color-tile" data-hex="${c.hex}"><div class="tile-color" style="background:${c.hex}"></div><div class="tile-info"><strong>${c.name}</strong><span>${c.hex}</span></div></button>`).join("");document.querySelectorAll(".color-tile").forEach(x=>x.onclick=()=>setColor(x.dataset.hex))}
fetch("colors.csv").then(r=>r.text()).then(t=>{colors=colors.concat(parseCSV(t));renderGrid();render()}).catch(()=>{renderGrid();render()});
render();